services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile.prod
    restart: always
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod

  nginx:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile.prod
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
